from aiogram.fsm.state import State, StatesGroup

class AdminMainSG(StatesGroup):
    verifying = State()
    mailing = State()
    change_status = State()
    phone = State()
    api_id = State()
    api_hash = State()
    app_version = State()
    device_model = State()
    system_version = State()
    lang_code = State()
    password = State()
    proxy_scheme = State()
    proxy_host = State()
    proxy_port = State()
    proxy_username = State()
    proxy_password = State()
    enter_code = State()
    parsing_link = State()
    inviting_delay = State()
    inviting_link = State()
    inviting_list = State()
    groups_delay = State()
    groups_list = State()
    groups_offer = State()
    private_delay = State()
    private_list = State()
    private_offer = State()
    leads_list = State()
    keyword_delay = State()
    keyword_list = State()
    bad_keyword_list = State()